1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np

# Create an empty 2x2 array
array = np.empty((2, 2))
print(array)


[[ 4.65909310e-310  0.00000000e+000]
 [-9.71091487e-214  6.79082799e-310]]


2. Initialize an all one array with size 4X2.

In [ ]:
import numpy as np

# Create a 4x2 array filled with ones
array_ones = np.ones((4, 2))
print(array_ones)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np

# Create an array with shape (3, 3), filled with the value 7
array_filled = np.full((3, 3), 7)
print(array_filled)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np

# Given array
given_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create a new array of zeros with the same shape and type as given_array
zeros_array = np.zeros_like(given_array)
print(zeros_array)


[[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np

# Given array
given_array = np.array([[4, 5, 6], [7, 8, 9]])

# Create a new array of ones with the same shape and type as given_array
ones_array = np.ones_like(given_array)
print(ones_array)


[[1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# Existing list
new_list = [1, 2, 3, 4]

# Convert the list to a NumPy array
np_array = np.array(new_list)

print(np_array)


[1 2 3 4]


1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np

# Create an array with values ranging from 10 to 49
array = np.arange(10, 50)
print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
import numpy as np

# Create an array with values from 0 to 8
array = np.arange(9)

# Reshape the array into a 3x3 matrix
matrix = array.reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np

# Create a random array of size 30
random_array = np.random.random(30)

# Calculate the mean of the array
mean_value = random_array.mean()

print("Random Array:", random_array)
print("Mean of the Array:", mean_value)


Random Array: [0.11744036 0.84219124 0.57612867 0.23887212 0.08951854 0.64254978
 0.89854532 0.10985256 0.82655012 0.82992212 0.76298577 0.12761042
 0.36281443 0.37114983 0.77056043 0.46390521 0.61277965 0.23864143
 0.43201424 0.77957064 0.12199605 0.58936612 0.15840686 0.3523476
 0.77178736 0.27375621 0.19215226 0.04794109 0.61615993 0.58779918]
Mean of the Array: 0.4601771848452687


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np

# Create a 10x10 array with random values between 0 and 1
random_array = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = random_array.min()
max_value = random_array.max()

print("Random 10x10 Array:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)


Random 10x10 Array:
[[0.10963287 0.94852823 0.2785078  0.30566265 0.90673672 0.82697493
  0.48931442 0.65110797 0.72691342 0.10372131]
 [0.29894357 0.71789685 0.43931969 0.97854432 0.27288097 0.69358094
  0.28010158 0.61372963 0.75662103 0.70831467]
 [0.09796146 0.23370946 0.19021717 0.1911498  0.64386869 0.56890101
  0.98145231 0.80112847 0.81835343 0.55452582]
 [0.88692581 0.8437087  0.17422141 0.59050069 0.43104336 0.21724424
  0.82104765 0.3117085  0.76104378 0.36768492]
 [0.89664711 0.33923806 0.0183427  0.60107271 0.96777756 0.22340347
  0.35466324 0.25082901 0.97953487 0.52296382]
 [0.56268998 0.49479554 0.58232061 0.76242705 0.96400366 0.99004287
  0.1896663  0.34298572 0.14616434 0.99215833]
 [0.49189151 0.82061959 0.36679223 0.18703696 0.89422559 0.82826989
  0.2813752  0.8113815  0.69273213 0.0901478 ]
 [0.04369987 0.50565482 0.9899375  0.15171771 0.23274708 0.58943769
  0.69230383 0.76543152 0.49250731 0.87283465]
 [0.05570992 0.2729554  0.0449153  0.14161207 0.29982588 0.5

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np

# Create a zero array of size 10
zero_array = np.zeros(10)

# Replace the 5th element (index 4) with 1
zero_array[4] = 1

print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
# Given array
arr = [1, 2, 0, 0, 4, 0]

# Reverse the array using slicing
reversed_arr = arr[::-1]

print(reversed_arr)


[0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np

# Define the size of the array (e.g., 5x5)
size = 5

# Create a 2D array filled with zeros
array = np.zeros((size, size), dtype=int)

# Set the border elements to 1
array[0, :] = 1  # Set top row to 1
array[-1, :] = 1  # Set bottom row to 1
array[:, 0] = 1  # Set left column to 1
array[:, -1] = 1  # Set right column to 1

print(array)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# Create an 8x8 matrix filled with zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern with 1s
checkerboard[1::2, ::2] = 1  # Set 1s in the alternating columns for even rows
checkerboard[::2, 1::2] = 1  # Set 1s in the alternating columns for odd rows

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Add the two arrays
result = x + y

print(result)


[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Subtract the two arrays
result = x - y

print(result)


[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Multiply the array x by an integer (for example, 2)
result_x = x * 2

# Multiply the array y by an integer (for example, 3)
result_y = y * 3

print("x multiplied by 2:")
print(result_x)

print("\ny multiplied by 3:")
print(result_y)


x multiplied by 2:
[[ 2  4]
 [ 6 10]]

y multiplied by 3:
[[15 18]
 [21 24]]


4. Find the square of each element of the array.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Square each element of the array x
square_x = x ** 2

# Alternatively, you can use np.square() to square each element
square_y = np.square(y)

print("Square of each element in x:")
print(square_x)

print("\nSquare of each element in y:")
print(square_y)


Square of each element in x:
[[ 1  4]
 [ 9 25]]

Square of each element in y:
[[25 36]
 [49 64]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])  # 2x2 array
y = np.array([[5, 6], [7, 8]])  # 2x2 array
v = np.array([9, 10])           # 1D array
w = np.array([11, 12])          # 1D array

# Dot product of v and w (1D arrays)
dot_v_w = np.dot(v, w)

# Dot product of x and v (2D array x and 1D array v)
dot_x_v = np.dot(x, v)

# Dot product of x and y (2D array x and 2D array y)
dot_x_y = np.dot(x, y)

# Print the results
print("Dot product of v and w:", dot_v_w)
print("Dot product of x and v:", dot_x_v)
print("Dot product of x and y:", dot_x_y)


Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])  # 2x2 array
y = np.array([[5, 6], [7, 8]])  # 2x2 array
v = np.array([9, 10])           # 1D array
w = np.array([11, 12])          # 1D array

# Concatenate x and y along rows (axis=0)
concat_x_y = np.concatenate((x, y), axis=0)  # Or you can use np.vstack((x, y))

# Concatenate v and w along columns (axis=1)
# Reshape v and w from 1D to 2D before concatenating
v_reshaped = v.reshape(-1, 1)  # Convert v to a 2D column vector
w_reshaped = w.reshape(-1, 1)  # Convert w to a 2D column vector
concat_v_w = np.concatenate((v_reshaped, w_reshaped), axis=1)  # Or use np.hstack((v_reshaped, w_reshaped))

# Print the results
print("Concatenated x and y along rows:")
print(concat_x_y)

print("\nConcatenated v and w along columns:")
print(concat_v_w)


Concatenated x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenated v and w along columns:
[[ 9 11]
 [10 12]]


Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

In [ ]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1, 1000001)]  # List with values from 1 to 1,000,000
list2 = [i for i in range(1000001, 2000001)]  # List with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform element-wise addition using a loop
result = [list1[i] + list2[i] for i in range(len(list1))]

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for element-wise addition: {end_time - start_time} seconds")


Time taken for element-wise addition: 0.2758946418762207 seconds


Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import numpy as np
import time

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1, 1000001)  # Array with values from 1 to 1,000,000
array2 = np.arange(1000001, 2000001)  # Array with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform element-wise addition using NumPy arrays
result = array1 + array2  # NumPy allows direct element-wise addition

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for element-wise addition using NumPy: {end_time - start_time} seconds")


Time taken for element-wise addition using NumPy: 0.0049457550048828125 seconds


Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

In [ ]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1, 1000001)]  # List with values from 1 to 1,000,000
list2 = [i for i in range(1000001, 2000001)]  # List with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform element-wise multiplication using a loop
result = [list1[i] * list2[i] for i in range(len(list1))]

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for element-wise multiplication using Python lists: {end_time - start_time} seconds")


Time taken for element-wise multiplication using Python lists: 0.18067455291748047 seconds


Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import numpy as np
import time

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1, 1000001)  # Array with values from 1 to 1,000,000
array2 = np.arange(1000001, 2000001)  # Array with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform element-wise multiplication using NumPy arrays
result = array1 * array2  # NumPy allows direct element-wise multiplication

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for element-wise multiplication using NumPy: {end_time - start_time} seconds")


Time taken for element-wise multiplication using NumPy: 0.004934549331665039 seconds


Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

In [ ]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1, 1000001)]  # List with values from 1 to 1,000,000
list2 = [i for i in range(1000001, 2000001)]  # List with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform dot product using a loop (element-wise multiplication and sum)
dot_product = sum(list1[i] * list2[i] for i in range(len(list1)))

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for dot product using Python lists: {end_time - start_time} seconds")


Time taken for dot product using Python lists: 0.18046092987060547 seconds


Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import numpy as np
import time

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1, 1000001)  # Array with values from 1 to 1,000,000
array2 = np.arange(1000001, 2000001)  # Array with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform dot product using NumPy arrays
dot_product = np.dot(array1, array2)

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for dot product using NumPy: {end_time - start_time} seconds")


Time taken for dot product using NumPy: 0.001987934112548828 seconds


Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

In [ ]:
import time

# Create two 1000x1000 matrices
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]  # 1000x1000 matrix
matrix2 = [[i - j for j in range(1000)] for i in range(1000)]  # 1000x1000 matrix

# Start measuring time
start_time = time.time()

# Perform matrix multiplication (result = matrix1 * matrix2)
result = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for matrix multiplication using Python lists: {end_time - start_time} seconds")


Time taken for matrix multiplication using Python lists: 251.66400718688965 seconds


Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

# Create two 1000x1000 matrices with random values
matrix1 = np.random.rand(1000, 1000)  # 1000x1000 matrix with random values
matrix2 = np.random.rand(1000, 1000)  # 1000x1000 matrix with random values

# Start measuring time
start_time = time.time()

# Perform matrix multiplication using NumPy
result = np.dot(matrix1, matrix2)  # You can also use matrix1 @ matrix2

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for matrix multiplication using NumPy: {end_time - start_time} seconds")


Time taken for matrix multiplication using NumPy: 0.16306018829345703 seconds
